---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-application-svc
  labels:
    app: mediawiki-application
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: {{ .Values.mediawikiApp.service.nodePort }}
  selector:
    app: mediawiki-application
