apiVersion: v1
kind: Service
metadata:
  name: mediawiki-database-svc
  labels:
    app: mediawiki-database
spec:
  #type: NodePort
  type: ClusterIP
  ports:
    - port: {{.Values.mediawikiDB.service.mariadbPort}}
      protocol: TCP
  selector:
    app: mediawiki-database

