---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-database-svc
  labels:
    app: mediawiki-database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mediawiki-database

