mediawikiApp:
  replicas: 1
  image: "mediawiki"
  containerPort: 80
  service:
    nodePort: 32244

mediawikiDB:
  replicas: 1
  image: "mariadb"
  database:
    name: "my_wiki"
    user: "wikiuser"
    password: "example"
  service:
    mariadbPort: 3306
